In [1]:
import pandas as pd
import numpy as np
from sklearn import ensemble, feature_extraction, preprocessing
import numpy as np
from sklearn import cross_validation
from sklearn.cross_validation import train_test_split
from sklearn.datasets import load_iris
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import f1_score


In [2]:
train=pd.read_csv('D:/new_git/OTT/data/train.csv')

In [3]:
training_labels = LabelEncoder().fit_transform(train['target'])
training_labels

array([0, 0, 0, ..., 8, 8, 8], dtype=int32)

In [4]:

train=train.drop('id', axis=1)
train=train.drop('target', axis=1)

In [5]:
X_train_raw, X_test_raw, y_train, y_test = train_test_split(train, training_labels)

In [125]:
y_train

array([0, 8, 3, ..., 7, 7, 0], dtype=int32)

In [69]:
#lbl_enc = preprocessing.LabelEncoder()
#y_train_lab = lbl_enc.fit_transform(y_train)
#y_test_lab =lbl_enc.fit_transform(y_test)

In [25]:
#targer = train.target.values
#train = train.drop('id', axis=1)
#train = train.drop('target', axis=1)
#test = test.drop('id', axis=1)

In [57]:
sv = SVC()
sv.fit(X_train_raw, y_train_lab)

NameError: name 'y_train_lab' is not defined

In [74]:
pred=sv.predict(X_test_raw)

In [81]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [83]:
print(confusion_matrix(pred, y_test_lab))
accuracy_score(pred, y_test_lab)

[[ 214    1    4    3    1   18   17   24   34]
 [  13 3515 1069  341   24   20   83   19   23]
 [   6  407  877  123    1    6   42    6    0]
 [   0   18    6  195    0    3    0    0    0]
 [   0    3    1    8  619    0    5    0    0]
 [  37    3    6   16    0 3266   50   38   41]
 [  19   22   30    7    1   45  404   20    2]
 [ 109   34   20   11    2  151  114 1947  125]
 [  96    3    3    0    1   38    3   35 1022]]


0.7795087265675501

In [33]:
from sklearn.feature_extraction import DictVectorizer as DV
vectorizer = DV( sparse = False )
tar = vectorizer.fit_transform( target )


AttributeError: 'str' object has no attribute 'items'

In [10]:
test2=test.values
test2.dtype

dtype('int64')

In [11]:
train2=train.values
train2.dtype

dtype('int64')

In [29]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


`%matplotlib` prevents importing * from pylab and numpy


In [102]:
from sklearn.metrics import roc_auc_score

In [6]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.multiclass import OneVsOneClassifier

In [9]:
from sklearn.grid_search import GridSearchCV
gbm = OneVsRestClassifier(GradientBoostingClassifier())
    
parameters = {
    
    "estimator__learning_rate": (.01, .05, 1),
        }

gs = GridSearchCV(gbm, param_grid=parameters, cv=5, score_func=f1_score, n_jobs=3, verbose=2)


#gbm=GradientBoostingClassifier(learning_rate=0.01)
#gbm.fit(train, labels)

In [10]:
gs.fit(X_train_raw, y_train)

C:\Users\dpa48077\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\grid_search.py:347: DeprecationWarning: Passing function as ``score_func`` is deprecated and will be removed in 0.15. Either use strings or score objects. The relevant new parameter is called ''scoring''.
  score_func=self.score_func)
[Parallel(n_jobs=3)]: Done   1 jobs       | elapsed:  5.7min
[Parallel(n_jobs=3)]: Done  15 out of  15 | elapsed: 26.5min finished


Fitting 5 folds for each of 3 candidates, totalling 15 fits


GridSearchCV(cv=5,
       estimator=OneVsRestClassifier(estimator=GradientBoostingClassifier(init=None, learning_rate=0.1, loss='deviance',
              max_depth=3, max_features=None, max_leaf_nodes=None,
              min_samples_leaf=1, min_samples_split=2, n_estimators=100,
              random_state=None, subsample=1.0, verbose=0,
              warm_start=False),
          n_jobs=1),
       fit_params={}, iid=True, loss_func=None, n_jobs=3,
       param_grid={'estimator__learning_rate': (0.01, 0.05, 1)},
       pre_dispatch='2*n_jobs', refit=True,
       score_func=<function f1_score at 0x0000000008C60A60>, scoring=None,
       verbose=2)

In [11]:
gs.best_score_

0.74074100816209343

In [57]:
from sklearn.grid_search import GridSearchCV
ec = SVC((kernel="poly"), n_jobs=4)


gs = ec.fit(train, labels)

In [12]:
preds_test=gs.predict(X_test_raw)

In [17]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(preds_test, y_test))

[[ 167    0    1    0    0    7    7   19   31]
 [  53 3517 1254  369   29   79  132   70   73]
 [   4  397  646   67    1    7   51    7   11]
 [   1   21   22  177    0    4    5    0    0]
 [   1   13    2    2  634    3    0    4    5]
 [  54   13    2   22    1 3361   46   68   71]
 [  19   25   39   11    0   35  378   11    4]
 [  93    8    8    3    0   67   59 1927   78]
 [  94    4    5    0    0   52    1   26  992]]


In [40]:
sample = pd.read_csv('D:/new_git/OTT/data/sampleSubmission.csv')
preds = pd.DataFrame(preds, index=sample.id.values, columns=sample.columns[1:])
preds.to_csv('py_gbm.csv', index_label='id')

In [20]:
test=pd.read_csv('D:/new_git/OTT/data/test.csv')
test=test.drop('id', axis=1)


In [28]:
predic_pro=gs.predict_proba(test)

C:\Users\dpa48077\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\utils\__init__.py:93: DeprecationWarning: Function multilabel_ is deprecated; Attribute multilabel_ is deprecated and will be removed in 0.17. Use 'y_type_.startswith('multilabel')' instead
  warnings.warn(msg, category=DeprecationWarning)


In [60]:
sample = pd.read_csv('D:/new_git/OTT/data/sampleSubmission.csv')
preds = pd.DataFrame(predic_pro, index=sample.id.values, columns=sample.columns[1:])
preds.to_csv('py_gbm_cv.csv', index_label='id')

In [59]:
predic_pro[1]

array([ 0.09706105,  0.27910058,  0.04511272,  0.01776929,  0.001398  ,
        0.48808379,  0.01438326,  0.03707493,  0.02001639])